import "./_styles/globals.css";
import NavBar from "./_components/NavBar";

export const metadata = {
  title: "UI Assessment",
  description: "Generated by Osahon",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
