import { Inter } from "next/font/google";
import "./_styles/globals.css";
import NavBar from "./_components/NavBar";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata = {
  title: "UI Assessment",
  description: "Generated by Osahon",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
